security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: ROLE_READER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path: /login_check
                username_parameter: _username
                password_parameter: _password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        main:
            pattern: ^/api
            provider: fos_userbundle
            stateless: true
            anonymous: true
            lexik_jwt: ~

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
#       - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, '%env(SECURITY_ALLOW_ORIGIN)%', 52.178.166.127, 213.41.98.10] }
#       - { path: ^/, role: ROLE_NO_ACCESS }
        - { path: ^/users, role: ROLE_USER, methods: [PUT] }
        - { path: ^/users/.*, role: ROLE_USER, methods: [GET] }
        - { path: ^/users, role: ROLE_ADMIN, methods: [GET] }
        - { path: ^/login, roles: ROLE_NO_ACCESS }
        - { path: ^/logout, roles: ROLE_NO_ACCESS }
