App\Domain\Tag\Entity\Tag:
    type: entity
    table: Tag
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        task:
            targetEntity: App\Domain\Task\Entity\Task
            inversedBy: tags
            joinColumn:
                name: task_id
                referencedColumnName: id