App\Domain\Task\Entity\Task:
    type: entity
    table: Task
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        dateCreation:
            type: datetime
        lastUpdate:
            type: datetime
    manyToOne:
            status:
                targetEntity: App\Domain\Status\Entity\Status
                inversedBy: tasks
                joinColumn:
                    name: status_id
                    referencedColumnName: id
    oneToMany:
            tags:
                targetEntity: App\Domain\Tag\Entity\Tag
                mappedBy: task
    manyToMany:
            categories:
                targetEntity: App\Domain\Category\Entity\Category
                joinTable:
                    name: tasks_categories
                    joinColumns:
                        task_id:
                          referencedColumnName: id
                    inverseJoinColumns:
                        category_id:
                          referencedColumnName: id