App\Domain\Task\Entity\Task:
    type: entity
    table: Task
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        date:
            type: datetime
        status:
            type: string
            length: 100
    manyToOne:
        category:
            targetEntity: App\Domain\Category\Entity\Category
            inversedBy: tasks
            joinColumn:
                name: category_id
                referencedColumnName: id
    oneToMany:
        tags:
            targetEntity: App\Domain\Tags\Entity\Tags
            mappedBy: task