App\Domain\User\Entity\User:
    type: entity
    table: User
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        fullName:
            type: string
        username:
            type: string
            unique: true
        email:
            type: string
            unique: true
        password:
            type: string
        roles:
            type: json